export const UNIVERSITIES = [
    "Institut Pertanian Bogor",
    "Institut Teknologi Sepuluh Nopember",
    "Universitas Abdurrab",
    "Universitas Ahmad Dahlan",
    "Universitas Airlangga",
    "Universitas Alkhairaat",
    "Universitas Andalas",
    "Universitas Baiturrahmah",
    "Universitas Batam",
    "Universitas Bengkulu",
    "Universitas Bosowa",
    "Universitas Brawijaya",
    "Universitas Cenderawasih",
    "Universitas Ciputra",
    "Universitas Diponegoro",
    "Universitas Gadjah Mada",
    "Universitas Gunadarma",
    "Universitas Gunung Jati",
    "Universitas Hang Tuah",
    "Universitas Hasanuddin",
    "Universitas HKBP Nommensen",
    "Universitas Indonesia",
    "Universitas Islam Bandung",
    "Universitas Islam Indonesia",
    "Universitas Islam Malang",
    "Universitas Islam Negeri Alauddin Makassar",
    "Universitas Islam Negeri Maulana Malik Ibrahim Malang",
    "Universitas Islam Negeri Sunan Ampel Surabaya",
    "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
    "Universitas Islam Negeri Walisongo Semarang",
    "Universitas Islam Sultan Agung",
    "Universitas Islam Sumatera Utara",
    "Universitas Jambi",
    "Universitas Jember",
    "Universitas Jenderal Achmad Yani",
    "Universitas Jenderal Soedirman",
    "Universitas Katolik Indonesia Atma Jaya",
    "Universitas Katolik Widya Mandala Surabaya",
    "Universitas Khairun",
    "Universitas Kristen Duta Wacana",
    "Universitas Kristen Indonesia",
    "Universitas Kristen Krida Wacana",
    "Universitas Kristen Maranatha",
    "Universitas Lambung Mangkurat",
    "Universitas Lampung",
    "Universitas Malahayati",
    "Universitas Malikussaleh",
    "Universitas Mataram",
    "Universitas Methodist Indonesia",
    "Universitas Muhammadiyah Jakarta",
    "Universitas Muhammadiyah Makassar",
    "Universitas Muhammadiyah Malang",
    "Universitas Muhammadiyah Prof. Dr. HAMKA",
    "Universitas Muhammadiyah Purwokerto",
    "Universitas Muhammadiyah Semarang",
    "Universitas Muhammadiyah Sumatera Utara",
    "Universitas Muhammadiyah Surabaya",
    "Universitas Muhammadiyah Surakarta",
    "Universitas Muhammadiyah Yogyakarta",
    "Universitas Mulawarman",
    "Universitas Muslim Indonesia",
    "Universitas Negeri Padang",
    "Universitas Negeri Semarang",
    "Universitas Negeri Surabaya",
    "Universitas Nusa Cendana",
    "Universitas Padjadjaran",
    "Universitas Palangka Raya",
    "Universitas Pattimura",
    "Universitas Pelita Harapan",
    "Universitas Pembangunan Nasional Veteran Jakarta",
    "Universitas Pembangunan Nasional Veteran Jawa Timur",
    "Universitas Pendidikan Ganesha",
    "Universitas Pendidikan Indonesia",
    "Universitas Prima Indonesia",
    "Universitas Riau",
    "Universitas Sam Ratulangi",
    "Universitas Sebelas Maret",
    "Universitas Sriwijaya",
    "Universitas Sultan Ageng Tirtayasa",
    "Universitas Sumatera Utara",
    "Universitas Surabaya",
    "Universitas Syiah Kuala",
    "Universitas Tadulako",
    "Universitas Tanjungpura",
    "Universitas Tarumanagara",
    "Universitas Trisakti",
    "Universitas Udayana",
    "Universitas Wahid Hasyim",
    "Universitas Warmadewa",
    "Universitas Wijaya Kusuma Surabaya",
    "Universitas YARSI"
];
